### ISSUE TITLE
chore: we should not require "starmaps" label on issues in order to render them (edit 2022-12-13 to include "not")

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/Starmap#109]
we should complete this after #96

**Comment by momack2** [comment]
Maybe I don't understand this - why do you want to require a starmaps label in order to render a milestone?

**Comment by juliaxbow** [comment]
Decision was made to revert this decision (i.e. remove the starmaps label requirement) on 2022-12-08. Reopening this issue.
