### ISSUE TITLE
Add roadmap area fill and stroke following color guide and designs in Figma

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/Starmap#138]
Header Row: #F8FBFF
Header Border (bottom): #A2D0DE / Solid / 1pt
Chart area: #F1F4F8
Quarter Timeline Markers: #A2D0DE / Dashed / 1pt

[Prototype](https://www.figma.com/file/7l5BAnM9ZDxDJePm3yIJFS/Roadmapping-Tool-MVP?node-id=345%3A583&t=SQ90NU5x7hdlbNI8-0) (screenshot below)
<img width="1143" alt="Screen Shot 2022-11-17 at 12 53 14 PM" src="https://user-images.githubusercontent.com/58958327/202557487-ffdd7346-00dc-4959-b2a8-aab1a4dc8cdd.png">

**Comment by SgtPooki** [comment]
Yea i'm fine with parking this until d3 is solved. Im really hoping we can get something consistently accurate for MVP.  

Just so you know, theres a few places that we're adding/subtracting based on hardcoded "months" "quarters" strings. Fixing those to use the currently selected dateGranularity might help a lot.

Also, we may want to resist using "endOf" and "startOf" as much as possible.

I'll try to take a peek at alignment again when i get async loading done

**Comment by juliaxbow** [comment]
There's an updated color scheme we should shift to (updated from both what is included in this issue and what is in MVP starmap site right now). 

### Notes:
- Today marker has already been addressed in https://github.com/pln-planning-tools/Starmap/issues/248
- Will address headers separately (I think we should shift towards moving quarters to the center of each month block - I know that's a change that'll come post-D3 but flagging here in case you're wondering why it looks different in the mock-up)

### How it should look:
![Button Toggle (Today Inactive)](https://user-images.githubusercontent.com/58958327/213645756-3d870055-e87e-4d94-a29b-9cadf5c67870.png)

### How it should look (redlined):
<img width="459" alt="Screen Shot 2023-01-20 at 12 04 14 AM" src="https://user-images.githubusercontent.com/58958327/213646345-b73550a6-1a4c-4d1f-bafb-3ceb50445082.png">

### Specs:
Header = Background Blue: #F9FCFF
Header Border, Roadmap Border, Timeline markers = Stroke Blue (Light): #A2D0DE, 1px
Roadmap Area = Background Gray: #FAFAFA
Corner radius = 10pt

### Figma File:
https://www.figma.com/file/7l5BAnM9ZDxDJePm3yIJFS/Roadmapping-Tool-MVP?node-id=1116%3A2096&t=FCLDNWjDTA7szvMt-0
(see also page titled colors & components)

**Comment by djmcquillan** [comment]
@juliaxbow @SgtPooki 

the designs only show the view with children.  Trying to get some thoughts on root issue detail view as we need a good way to show separation of the themes/milestones with the new style guide updates

<img width="1017" alt="Screen Shot 2023-01-27 at 3 04 24 PM" src="https://user-images.githubusercontent.com/10619673/215222543-2e94766b-4882-4862-a7f4-7e2a4059b15f.png">
