### ISSUE TITLE
Feature Request: Add Search Functionality to find/discover other team roadmaps

### ISSUE THREAD

**Issue by davidd8** [pln-planning-tools/Starmap#239]
Context:

Right now, it's very difficult to find other teams' roadmaps without knowing the root github issue. Although, the Notion directory page helps alleviate some of this, the user still needs to know what team to look up, ahead of time. Adding dependencies may help, but a full-text search would make it even easier.

Feature Request:
- Have a full-text search bar that returns a list of roadmaps that match the query string (the match should include the children)
- Clicking on the result should bring up the corresponding roadmap with highlighted text matches.

**Comment by SgtPooki** [comment]
@davidd8 This would be valuable, but we don't currently have any datastore of issues to do any searching over, and we're not using auth provided by the user either, so this would easily become unusable from the centrally used application.

GitHub is our source of truth, so the best thing that is in alignment with the direction of this project is https://github.com/pln-planning-tools/Starmap/issues/105, which still doesn't support the discovery aspect, only the UX aspect of easily re-selecting issues you've already viewed.

We could potentially run an indexer on all issues across all repos in all organizations in the PL, and indexing them for search by us, but that alone would require a team to maintain it.

If you have some solution I'm not thinking of, I'm happy to discuss it further, but I'm closing this for now.
