### ISSUE TITLE
Feat: Update view mode toggle from tabs to toggle button

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/Starmap#246]
**Details**
- Follow up to #99. 
- Starmap allows you to toggle between detailed and overview. In December we received feedback that the tabs were not intuitive and were asked to switch from tab (current) to toggle button.
- Ultimately we will want to add "List view" in as well

**Prototype**
- Screenshot
 <img width="742" alt="Screen Shot 2023-01-05 at 1 32 40 AM" src="https://user-images.githubusercontent.com/58958327/210747717-78ddb984-a272-4221-8994-332f8b40ef1c.png">
- In action

https://user-images.githubusercontent.com/58958327/210748481-dc349495-9c0a-4263-bfac-444873b98c4d.mov

**Specs**
- Inspect in Figma [here](https://www.figma.com/file/7l5BAnM9ZDxDJePm3yIJFS/Roadmapping-Tool-MVP?node-id=1184%3A2596&t=2XCIcZWxJdgvQRX0-0)
- Note that each button has a three states (active/clicked, hover, inactive)

@djmcquillan or @SgtPooki thoughts on this update? Lower priority than other issues

**Comment by djmcquillan** [comment]
I like this design, it is way clearer to me what the tab buttons are used for with this layout.
