### ISSUE TITLE
Update milestone card to match new card design and specs

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/Starmap#273]
### Background: 
Following feedback session on 12/8 request was made to update the milestone card design to place emphasis on issue title, while still allowing for all elements. Primary requests 
- Mute/dull github icon in milestone card
- Blend milestone card into background so it is not as prominent

### Requested Changes:
**Structural**
- Change progress indicator from filling up the full card to a smaller progress bar/status indicator underneath the issue title
- Move the github icon to the bottom right of the milestone card

**Font Colors**
- Change the font color of the ETA and GitHub icon to rgba(163, 163, 163, 1)
- Where issues have child milestones (ie are clickable) change title font color to "link blue" rgba(73, 135, 189, 1)
- Where issues do not have child milestones (ie are not clickable) leave font color unchanged

**Stroke**
- Change the stroke color around all milestone cards to rgba(239, 239, 239, 1)
   - This means that the stroke color and size should be the same whether cards are clickable or not
- Where issues have child milestones (ie are clickable) on hover, change the stroke color to "spotlight blue" rgba(31, 165, 255, 1)

### Requested changes with visuals:
![Milestone Card Specs](https://user-images.githubusercontent.com/58958327/213332868-8c23095d-52d3-4d3e-b352-d2cb95be1464.png)

![Milestone Card Spacing](https://user-images.githubusercontent.com/58958327/213332872-4a2ceae2-93ad-4e7f-af19-7616d474b756.png)

### Prototype preview (hover state):
https://www.figma.com/proto/7l5BAnM9ZDxDJePm3yIJFS/Roadmapping-Tool-MVP?node-id=1116%3A2096&scaling=min-zoom&page-id=898%3A1838&starting-point-node-id=1145%3A3000

### Figma: 
https://www.figma.com/file/7l5BAnM9ZDxDJePm3yIJFS/Roadmapping-Tool-MVP?node-id=1368%3A2733&t=tEG7wDsvzh5BFWmZ-0

**Comment by juliaxbow** [comment]
@djmcquillan quick flag - if you need to break this into different tasks go for it. For example, the progress bar change might be its own issue as I'm not sure how time intensive that will be. Other changes to the card mentioned in this issue take priority over the progress bar change IMO. But you tell me. Thanks!

**Comment by SgtPooki** [comment]
i'm really not sure i'm a fan of how this looks overall. see https://github.com/pln-planning-tools/Starmap/pull/282

**Comment by juliaxbow** [comment]
@SgtPooki which part do you most dislike? The new status indicator? 

Did some (admittedly minimal) a/b testing and this style was most preferred while checking all of the boxes for 1) focus on title 2) more discreet date/GitHub link and 3) readability of the card with the status indicator

Can/maybe should open it up to the channel to see what the group thinks, though!

**Comment by SgtPooki** [comment]
@juliaxbow I don't really know how to verbalize it.. it just seems... ephemeral.. like the progress bars are floating with any of the elements inside the card could float away at any moment.. 

the comments I'm making are based on this rendering: 

![image](https://user-images.githubusercontent.com/1173416/214732270-598bc336-68bf-428c-a3c1-91ae9ca78dca.png)

### Things I dislike

* the different sections in detailed view don't have any separation, so there are seemingly ambiguous texts, progress-bars, and github icons inside each section and no way to discern each section from the other.
* stacked cards don't seem to have an appropriate separation; they look weird next to each other. 
* The progress bar (when visible) acts as a sort of underline for the milestone title (pro and con)
* The date text (bottom left of card) is not very visible
* The github icon is too muted?

### Things I like

* They take up less vertical space
* The progress bar (when visible) acts as a sort of underline for the milestone title (pro and con)

### ideas for change

* Slight background color change so we can identify container more easily
*  progress bar: 
    * option 1: border when empty, no-border when there is progress
    * option 2: always a border
    * option 3: If there are no children, display Open/closed
    * option 4: Display number of children open & closed.
* make github icon slightly darker
* make date text in bottom left slightly darker (or remove it altogether?)

**Comment by djmcquillan** [comment]
- side by side I lean more toward the new designs but admit when the progress of every issue is 100% it looks a little off or could use another indicator of completed 

- I Updated the progress for the screenshot below and the progress bar seems to do its job well(although option 5 would be a cool design)

<img width="963" alt="Screen Shot 2023-01-25 at 5 33 41 PM" src="https://user-images.githubusercontent.com/10619673/214736382-e2eb59f6-1880-419b-856d-f8289c2d449d.png">

**Comment by SgtPooki** [comment]
@djmcquillan thanks for the feedback. any thoughts on the other suggestions (dates/github icon)?

**Comment by SgtPooki** [comment]
Also, for option five.. having "dots" for children could look pretty cool too.

**Comment by djmcquillan** [comment]
> @djmcquillan thanks for the feedback. any thoughts on the other suggestions (dates/github icon)?

I am fine with making them a slightly darker so they do not seem disabled.  If the idea was to highlight titles and increase readability/progress then I think it is achieved  with the rearrangement.
