### ISSUE TITLE
docs: discuss formatting change

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/Starmap#288]
see https://github.com/pln-planning-tools/Starmap/pull/287

**Comment by AlexxNica** [comment]
@SgtPooki can you elaborate on this issue? What formatting changes are you referring to, and what should we discuss about it? I looked at the multiple issues and PRs interlinked but didn't quite understand.

**Comment by SgtPooki** [comment]
You're right this one can be closed because the format used in the related PR is what we always used in the code. Also, that format is being deprecated in favor of github tasklists.
