### ISSUE TITLE
Bug: issue with content height and scrollable roadmap

### ISSUE THREAD

**Issue by djmcquillan** [pln-planning-tools/Starmap#289]
there seems to be some issues with the height of the page/scrollable area of the roadmap grids making the page seem jumpy when scrolling.  Ideally only the roadmap section would be scrollable if the content overflows.

https://user-images.githubusercontent.com/10619673/214993708-92dd5230-953b-4fe2-8d9d-e2f923bc5616.mov

**Comment by djmcquillan** [comment]
@SgtPooki i think we had an issue to set height dynamically but I could not find it to link

**Comment by SgtPooki** [comment]
Losing this as it should be fixed by #237
