### ISSUE TITLE
Feature: Support GitHub tasklists in root node and child milestone issue template

### ISSUE THREAD

**Issue by p-shahi** [pln-planning-tools/Starmap#298]
GitHub recently released its tasklist feature. I propose that the starmap issue templates support the tasklist syntax for seamless integration with GitHub issues. 

Here is the expected syntax https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists#creating-tasklists and rendered output: 

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by BigLep** [comment]
@p-shahi : I think this is a duplicate of https://github.com/pln-planning-tools/Starmap/issues/245 (or at least related)

**Comment by p-shahi** [comment]
Closing this as a duplicate of #245
