### ISSUE TITLE
All roadmap items have completed green bar - despite not being complete?

### ISSUE THREAD

**Issue by momack2** [pln-planning-tools/Starmap#302]
![image](https://user-images.githubusercontent.com/618519/216995498-b2e1a5c4-f4b8-41c5-b054-da1803500648.png)

I'm confused why all the items in this roadmap are showing as completed? AFAIK many of them have ETAs in the future, and the issue is still opened - so not sure how we're getting the data to think they should be complete...

- https://starmap.site/roadmap/github.com/protocol/engres/issues/5#simple
- https://github.com/filecoin-project/rust-fil-proofs/issues/1644

IMHO - using the closing of the issue, or adding some "status: complete" tag would be good enough to see an issue is landed - but these shouldn't be....

**Comment by SgtPooki** [comment]
i'll be working on this one today

**Comment by SgtPooki** [comment]
Yiannis reports seeing empty progress bars where they should be showing some progress now: 

https://filecoinproject.slack.com/archives/C0418TBQ9CH/p1675888144792229?thread_ts=1675886012.689499&cid=C0418TBQ9CH

- https://starmap.site/roadmap/github.com/protocol/probelab/issues/1#simple
- https://github.com/protocol/probelab/issues/1
