### ISSUE TITLE
bug - "Today" marker inaccurate 

### ISSUE THREAD

**Issue by quickhatche** [pln-planning-tools/Starmap#351]
Viewing on EngRes Theme-Based 2023 Roadmap -  https://starmap.site/roadmap/github.com/protocol/engres/issues/9#detail

Looks like "Today" marker is not on the right month

![image](https://user-images.githubusercontent.com/29782505/231571481-b2f8c5e1-946d-4669-bc16-57fdbee21aad.png)

**Comment by SgtPooki** [comment]
Also off in IPFS Thing demo by Bastien for Fission roadmap (Link TBD)

**Comment by SgtPooki** [comment]
@quickhatche thanks for submitting. Will be addressing this after #350

**Comment by quickhatche** [comment]
@SgtPooki Looking at the page again and the Today marker is on future date
![Screenshot 2023-05-09 at 6 02 22 PM](https://github.com/pln-planning-tools/Starmap/assets/29782505/99eb6fab-1411-41d3-807b-e1791ab93d30)

**Comment by quickhatche** [comment]
![Uploading Screenshot 2023-05-09 at 6.00.01 PM.png…]()
