### ISSUE TITLE
Add license files

### ISSUE THREAD

**Issue by AlexxNica** [pln-planning-tools/Starmap#78]

**Comment by SgtPooki** [comment]
standard licensing files are Apache2.0 OR MIT as specified by ipfs/aegir

**Comment by SgtPooki** [comment]
https://github.com/ipfs/aegir/blob/99fd171fbb051f173b5ed75f36466a5187b3056e/package.json#L5
https://github.com/ipfs/aegir/blob/master/LICENSE
https://github.com/ipfs/aegir/blob/master/LICENSE-APACHE
https://github.com/ipfs/aegir/blob/master/LICENSE-MIT
